### ISSUE TITLE
java.time objects aren't able to fake time

### ISSUE THREAD

**Issue by sanjay-chittar** [faketime-java/faketime#3]
When I use the agent for faking time, only System.currentTimeMillis() is able to fake the time, but java.time objects aren't.
When I looked further into the problem I noticed that the lack of override in function fakeGetNanoTimeAdjustment when faketime.offset.ms property is set is the cause.

I have referenced the line here:

https://github.com/faketime-java/faketime/blob/fa30cc5292f9453769d6c15cbdc9c31751ea7ab2/modules/agent/src/main/c/agent.c#L68

What I noticed is java.time classes like LocalDate LocalDateTime are using an implementation of Clock class to fetch an Instant object. The default implementation SystemClock is using both System.currentTimeMillis and VM.getNanoTimeAdjustment to create Instant object, since there is no override for method VM.getNanoTimeAdjustment, the time gets reset to the actual time, even though System.currentTimeMillis is returning fake time.

**Comment by sanjay-chittar** [comment]
I did a local fix in my machine by adding the below code

`else if (getOffsetFromSystemProperty(jni_env, &propertyValue)) {

    jlong retVal = (realGetNanoTimeAdjustment(jni_env, klass, offsetInSeconds) + propertyValue * 1000000);

    fprintf(stdout, "FakeTime:fakeGetNanoTimeAdjustment called returning value %ld with original value %ld with offset %ld with propertyValue %ld\n", retVal, realGetNanoTimeAdjustment(jni_env, klass, offsetInSeconds) , offsetInSeconds, propertyValue);

    return retVal;
  }`

**Comment by sanjay-chittar** [comment]
I tried a simple fix by adding the below code in method fakeGetNanoTimeAdjustment

```
else if (getOffsetFromSystemProperty(jni_env, &propertyValue)) {

    jlong retVal = (realGetNanoTimeAdjustment(jni_env, klass, offsetInSeconds) + propertyValue * 1000000);

    fprintf(stdout, "FakeTime:fakeGetNanoTimeAdjustment called returning value %ld with original value %ld with offset %ld with propertyValue %ld\n", retVal, realGetNanoTimeAdjustment(jni_env, klass, offsetInSeconds) , offsetInSeconds, propertyValue);

    return retVal;
  }
```

**Comment by mihhail-lapushkin** [comment]
Thanks!

Could you make a PR together with a test that verifies this?

**Comment by mihhail-lapushkin** [comment]
https://github.com/faketime-java/faketime/pull/5
