### ISSUE TITLE
No release with latest fixes available.

### ISSUE THREAD

**Issue by reaver585** [faketime-java/faketime#6]
Hey there.
Latest available version of the agent, 0.8.0, was released in 2018 and it does not have last fixes that fix the `realGetNanoTimeAdjustment` issue for setting the offset.

Could you please release it, or at the very least, provide some instructions on how to build the agent locally?
Thanks a lot in advance, and sorry if I missed anything.

**Comment by mihhail-lapushkin** [comment]
Hey!

Sorry. I am not actively involved in the Java ecosystem anymore.

IIRC the maven build should produce an agent binary locally for your operating system. The source is all there and it's using `gcc` on Unix to compile. On Windows you will need `Microsoft Visual Studio 14.0`.

Let me know if you run into issues. I will try to help in this thread.

**Comment by reaver585** [comment]
Thanks a lot @mihhail-lapushkin. Me and my colleague will try to build it ourselves today. If you don't mind, I will keep this issue open for now until we have this sorted, to be able to reach out to you.

FYI @fominv

**Comment by fominv** [comment]
I am not really familiar with Maven, so I compiled the agent locally via gcc: 

```sh
gcc -O2 -fPIC -pthread -D_LP64=1 -c -I $JAVA_HOME/include -I $JAVA_HOME/include/linux src/main/c/agent.c
gcc -z defs -static-libgcc -shared -o src/main/resources/linux_x86_64/libfaketime agent.o -lc
```

With the modified C code the offset works and is reflected in `Instant.now()` calls.

@mihhail-lapushkin Thanks for library :) and feel free to close!
